### ISSUE TITLE
multiple definition of .....

### ISSUE THREAD

**Issue by ZwilleSmutje** [Seeed-Studio/SGP30_Gas_Sensor#2]
> Error: 
> /tmp/179880365/build/libraries/sensirion_sps_0_0_6/sensirion_hw_i2c_implementation.cpp.o:/home/builder/opt/libraries/latest/sensirion_sps_0_0_6/sensirion_hw_i2c_implementation.cpp:104: first defined here
> collect2: error: ld returned 1 exit status
> exit status 1

In all examples it says:
#include <Arduino.h>
**#include "sensirion_common.h"**
#include "sgp30.h"

Cross out the #include "sensirion_common.h", so that in every example it only says:
#include <Arduino.h>
#include "sgp30.h"

**Comment by Lesords** [comment]
Hello,

I'm very sorry to have kept you waiting so long.

Do you still have this problem now?

**Comment by Lesords** [comment]
Hello,

I\'m going to close this issue, feel free to re-open it if you have any other questions.

[Autocommentary]
