### ISSUE TITLE
SGP fails when another I2C Device is connected 

### ISSUE THREAD

**Issue by Lenardgeorge** [Seeed-Studio/SGP30_Gas_Sensor#3]
Trying to display the value of C02 levels to an RGB LCD display and the minute I connect the LCD through the I2C port at the same time the initialisation of the SGP Sensor fails. Heres what I get when I run the I2C Scanner example 

![Screenshot 2022-11-24 at 13 22 47](https://user-images.githubusercontent.com/13812425/203784074-b0cd21dd-8efc-44be-b42a-1ce81cef8687.png)

**Comment by Lesords** [comment]
Hello,

I'm very sorry to have kept you waiting so long.

Do you still have this problem now?

**Comment by Lesords** [comment]
Hello,

I\'m going to close this issue, feel free to re-open it if you have any other questions.

[Autocommentary]
