### ISSUE TITLE
Add library to Arduino Library Manager

### ISSUE THREAD

**Issue by per1234** [Seeed-Studio/SGP30_Gas_Sensor#4]
Adding this library to the [Arduino Library Manager](https://docs.arduino.cc/software/ide-v1/tutorials/installing-libraries#using-the-library-manager) will make it easier for users to install and update the library.

In order to do this, only two actions are required:

1. Make a [release](https://docs.github.com/en/github/administering-a-repository/releasing-projects-on-github/managing-releases-in-a-repository) or [tag](https://git-scm.com/docs/git-tag) in this repository.
1. Submit the library to [the Arduino Library Registry](https://github.com/arduino/library-registry#adding-a-library-to-library-manager).

I would be happy to take responsibility for task (2) in the above list, and I have already verified that the library is compliant with all [the requirements for submitted libraries](https://github.com/arduino/library-registry/blob/main/FAQ.md#what-are-the-requirements-for-a-library-to-be-added-to-library-manager).

Task (2) is dependent on the completion of task (1) and only someone with write permissions in this repository can take care of task (1).

---

Please let me know if you have any questions or concerns.

**Comment by Lesords** [comment]
Hello,

I'm very sorry to have kept you waiting so long.

I will solve the problem you mentioned later.

**Comment by Lesords** [comment]
Sorry, I've been busy lately.

The release package has been released and the current library link has been submitted in the library-registry.

This library will be available for installation via Library Manager within a day's time.

You can check the logs from the Library Manager indexer for this library here:
http://downloads.arduino.cc/libraries/logs/github.com/Seeed-Studio/Seeed_Arduino_SGP30/

By the way, the repository name has now been changed to Seeed_Arduino_SGP30.

**Comment by Lesords** [comment]
I'm going to close this issue, feel free to re-open it if you have any other questions.
